<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PipAndIvory.Domain</RootNamespace>
    <AssemblyName>PipAndIvory.Domain</AssemblyName>
  </PropertyGroup>

  <!-- Package References -->
  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

</Project>
